In [1]:
import pandas as pd
import sqlite3

db_path = "SQLite-db/sessions.db"
conn = sqlite3.connect(db_path)

In [ ]:
viewer_sessions_df = pd.read_sql("""
SELECT * 
FROM viewer_sessions 
LIMIT 10
""", conn)
viewer_sessions_df.head()

,tv_day,channel_id,viewer_id,session_start,session_finish,session_duration,model_version,device_id,session_id,delivery_id,resolution_id,session_source,timeshifted_start,target_groups
0,2025-09-12,0,21038_7,2025-09-12 19:02:38,2025-09-12 19:24:19,1302,4.30.2_spin+at.20250829113426,c7072258-2ec8-48ef-8722-582ec8a8ef35,177d3a1d-5153-47c9-bd3a-1d515397c9a8,2,2,tracked,None,"b""\xf0\xf1\x8d%`\x02\x00\x00\xb03$'`\x02\x00\x00"""
1,2025-09-12,0,28170_15,2025-09-12 17:31:55,2025-09-12 17:31:58,4,4.30.2_spin+at.20250829113426,c7a84610-ce18-4cef-a846-10ce182cef44,5d129e10-9fa8-42d7-929e-109fa872d761,1,2,tracked,None,"b""\xf0\xf1\x8d%`\x02\x00\x00p6$'`\x02\x00\x000..."
2,2025-09-12,0,21735_21,2025-09-12 13:07:18,2025-09-12 14:54:37,6440,4.30.2_spin+at.20250829113426,c80fe630-2f99-4cb3-8fe6-302f996cb3ba,9706dcb8-ea84-4890-86dc-b8ea84d8904d,1,2,tracked,None,"b""p6$'`\x02\x00\x00\xf0 $'`\x02\x00\x00\xf0\xf..."
3,2025-09-12,0,29452_5,2025-09-12 14:07:27,2025-09-12 14:09:44,138,4.30.2_spin+at.20250829113426,c978af24-69ee-495b-b8af-2469eea95bd5,6b8ed148-9d8f-4eb4-8ed1-489d8f1eb412,1,2,tracked,None,"b""\xf0\xf1\x8d%`\x02\x00\x00\xb03$'`\x02\x00\x00"""
4,2025-09-12,0,16390_26,2025-09-12 18:15:15,2025-09-12 18:15:24,10,4.30.2_spin+at.20250829113426,cbd23888-71d9-433b-9238-8871d9133b45,6cda6098-846f-4422-9a60-98846f44226e,1,2,tracked,None,"b""\xf0\xf1\x8d%`\x02\x00\x00\xf0,$'`\x02\x00\x00"""

In [4]:
viewer_sessions_df = pd.read_sql("""
SELECT session_id, count(1)
FROM viewer_sessions 
where viewer_id = '16349_15'
group by session_id
order by count(1) desc
LIMIT 10
""", conn)
viewer_sessions_df.head()

                             session_id  count(1)
0  f58bc61e-a20d-4650-8bc6-1ea20de650a2         2
1  ef6d5d92-360c-49bf-ad5d-92360c99bf5c         2
2  eb18acf4-4713-4afa-98ac-f447135afa4d         2
3  dc152d09-a615-416d-952d-09a615016d48         2
4  d81abe7c-f654-4098-9abe-7cf65460980e         2

In [2]:
viewer_sessions_df = pd.read_sql("""
SELECT * 
FROM viewer_weights
LIMIT 100
""", conn)
viewer_sessions_df.head()

                   model_version    viewer target_group  viewer_weight
0  4.30.2_spin+at.20250829113426  16137_15   1-12_17-h0      10.665026
1  4.30.2_spin+at.20250829113426  16273_27   1-12_17-h0      29.488480
2  4.30.3_spin+at.20250829122618   16273_9   1-12_17-h0      87.393131
3  4.30.2_spin+at.20250829113426  16349_15   1-12_17-h0      47.720427
4  4.30.2_spin+at.20250829113426  16349_22   1-12_17-h0      31.938868

In [ ]:
import matplotlib.pyplot as plt

df = sessions_df.sort_values("ts")

for group, g in df.groupby("target_group"):
    plt.plot(g["ts"], g["demo_sessions"], label=group)

plt.xlabel("ts")
plt.ylabel("demo_sessions")
plt.title("Target group sessions over time")
plt.legend(title="target_group")
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

KeyError: 'demo_sessions'